=== arvicco/nabu/test/fixtures/mw/mw.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 04-25-2022. Add 'i' as child of 'ls'. For pwkvn -->
<!-- 01-22-2024. For dictlo = pe, Exclude the further 'pe' tag.-->
<!-- 02-05-2024. Change pe tag to per, and remove logic re dictlo = pe -->
<!-- 01-14-2026. sab element added for ap -->
<!-- 06-12-2026. add 's' as child of 'ls'  for pwg -->
<!ELEMENT  mw (H1 | H2 | H3 | H4 | H1A | H2A | H3A | H4A |
H1B | H2B | H3B | H4B | H1C | H2C | H3C | H4C | H1E | H2E | H3E | H4E)*>
<!ELEMENT H1 (h,body,tail) >
<!ELEMENT H2 (h,body,tail) >
<!ELEMENT H3 (h,body,tail) >
<!ELEMENT H4 (h,body,tail) >
<!ELEMENT H1A (h,body,tail) >
<!ELEMENT H2A (h,body,tail) >
<!ELEMENT H3A (h,body,tail) >
<!ELEMENT H4A (h,body,tail) >
<!ELEMENT H1B (h,body,tail) >
<!ELEMENT H2B (h,body,tail) >
<!ELEMENT H3B (h,body,tail) >
<!ELEMENT H4B (h,body,tail) >
<!ELEMENT H1C (h,body,tail) >
<!ELEMENT H2C (h,body,tail) >
<!ELEMENT H3C (h,body,tail) >
<!ELEMENT H4C (h,body,tail) >
<!ELEMENT H1E (h,body,tail) >
<!ELEMENT H2E (h,body,tail) >
<!ELEMENT H3E (h,body,tail) >
<!ELEMENT H4E (h,body,tail) >
<!ENTITY % body_elts "b | i | s |div | alt | symbol | F |  br | H | root |lb | P | lang | sup | pic | ls |ab|lbinfo|s1|lex|vlex|C|Poem|note|nsi |sic|is|bot|VN|type|hom|mark|edit|bio|etym|pb|pc|pcol|shortlong|srs|info|ns|span|per|chg|old|new|gk|heb|iw|zoo|tib|ger|fr|ed|ms|lat|toch|arab|rus|mong|ocs|mng|abot|pe|azoo|enum|zen|num|cl|listinfo|sab" >
<!ELEMENT h  (key1,key2,hom?)>
<!ELEMENT key1 (#PCDATA) >
<!ELEMENT key2 (#PCDATA )>
<!ELEMENT hom (#PCDATA)>
<!ELEMENT body (#PCDATA  | %body_elts;)*>
<!ELEMENT br EMPTY >
<!ELEMENT lb EMPTY>
<!ELEMENT F (#PCDATA  | %body_elts;)*>
<!ELEMENT s (#PCDATA | br | srs | shortlong | chg)*>
<!ELEMENT H EMPTY>
<!ELEMENT P EMPTY>
<!ELEMENT b (#PCDATA  | %body_elts;)*>
<!ELEMENT i (#PCDATA  | %body_elts;)*>
<!ELEMENT symbol (#PCDATA)>
<!ELEMENT div (#PCDATA  | %body_elts;)*>
<!ELEMENT chg (#PCDATA  | old | new)*>
<!ELEMENT old (#PCDATA  | %body_elts;)*>
<!ELEMENT new (#PCDATA  | %body_elts;)*>
<!ELEMENT span (#PCDATA  | %body_elts;)*>
<!ELEMENT tail (#PCDATA | L | pc |hwtype|info|listinfo)*>
<!ELEMENT L (#PCDATA) >
<!ELEMENT pc (#PCDATA) >
<!ELEMENT cl (#PCDATA) > <!-- 12-20-2023. md. <cl>III</cl> 3rd class verb -->
<!ELEMENT iw (#PCDATA) >
<!ATTLIST iw n CDATA #IMPLIED>
<!ELEMENT hwtype EMPTY>
<!ELEMENT alt (#PCDATA | s)*>
<!ELEMENT sup (#PCDATA |s)*>
<!ELEMENT lang (#PCDATA | %body_elts; )* >
<!ELEMENT gk (#PCDATA) > <!-- Greek text, GRA, mw-->
<!ELEMENT heb (#PCDATA) > <!-- Hebrew text, GRA-->
<!ELEMENT tib (#PCDATA) > <!-- Tibetan text, bhs-->
<!ELEMENT ger (#PCDATA | i | ab)* > <!-- German text, bhs-->
<!ELEMENT fr (#PCDATA | i | ab | chg)* > <!-- French text, bhs-->
<!ELEMENT arab (#PCDATA) > <!-- Arabic text, PW, mw-->
<!ELEMENT rus (#PCDATA) >  <!-- Russian text, PW-->
<!ELEMENT mong (#PCDATA) >  <!-- Mongolian text, PW-->
<!ELEMENT ocs (#PCDATA) >  <!-- Old Church Slavonic text, PWG-->
<!ELEMENT mng (#PCDATA) >  <!-- meaning indicator, PWG-->
<!ELEMENT abot (#PCDATA) >  <!-- botanical authority abbreviation, PWG-->
<!ELEMENT pe (#PCDATA) >  <!-- person ending/verbal ending, PWG-->
<!ELEMENT azoo (#PCDATA) >  <!-- zoological authority abbreviation, PWG-->
<!ELEMENT enum (#PCDATA) >  <!-- enumeration marker, PWG-->
<!ELEMENT zen (#PCDATA) >  <!-- Zend/Avestan text, PWG-->
<!ELEMENT num (#PCDATA) >  <!-- number abbreviation, PWG-->
<!ELEMENT ed (#PCDATA) > <!-- edition bhs-->
<!ELEMENT ms (#PCDATA) > <!-- manuscript bhs-->
<!ELEMENT lat (#PCDATA | i | ab)* > <!-- latin text, bhs-->
<!ELEMENT toch (#PCDATA) > <!-- Tocharian text bhs-->
<!ELEMENT pic EMPTY >
<!ELEMENT s1 (#PCDATA)*>
<!ELEMENT lex (#PCDATA | %body_elts;)* >
<!ELEMENT vlex EMPTY >
<!ELEMENT Poem (#PCDATA  | %body_elts;)*>
<!ELEMENT note EMPTY>
<!ELEMENT nsi (#PCDATA)*>
<!ELEMENT is (#PCDATA)*>
<!ELEMENT sic EMPTY >
<!ELEMENT bot (#PCDATA  | %body_elts;)*>
<!ELEMENT root EMPTY >
<!--
<!ELEMENT ls (#PCDATA | %body_elts;)*>
mw requires also ab|s1|ns
pwg requires also is
lan requires also sup
bhs requires also lang
  -->
<!ELEMENT ls (#PCDATA |ab|s1|ns|is|i|sup|lang|lb | chg|s|lex)*>
<!ELEMENT ab (#PCDATA | chg)*> <!-- general abbreviation -->
<!ELEMENT per (#PCDATA)> <!-- person 'abbreviation' (1., etc) -->
<!ELEMENT lbinfo EMPTY>
<!ELEMENT C EMPTY>
<!ELEMENT VN (#PCDATA | %body_elts; )* >
<!ELEMENT type (#PCDATA)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT listinfo (#PCDATA)>
<!ELEMENT mark EMPTY >
<!ELEMENT edit EMPTY >
<!ELEMENT etym (#PCDATA | %body_elts; )* >
<!ELEMENT ns (#PCDATA | %body_elts; )* >
<!ELEMENT sab (#PCDATA | %body_elts; )* >
<!ELEMENT bio (#PCDATA )* >
<!ELEMENT zoo (#PCDATA | %body_elts; )* >
<!ATTLIST zoo n CDATA #IMPLIED>
<!ELEMENT pb (#PCDATA) >
<!ELEMENT pcol (#PCDATA) >
<!ELEMENT shortlong EMPTY>
<!ELEMENT srs EMPTY >

<!ATTLIST symbol n CDATA #REQUIRED>
<!ATTLIST div name CDATA #IMPLIED>
<!ATTLIST div n (P | 2 | 3 | lb |pfx |1 | I | xe | xs |p|H|P1|HI|F|NI|m|o|4|v|E|Poem|Picture|lex|to|vp|Q|TS|Pf|W|conj|zz|yy|pW|pp) #IMPLIED>
<!ATTLIST span style CDATA #IMPLIED>
<!ATTLIST span class CDATA #IMPLIED>
<!ATTLIST chg type CDATA #IMPLIED>
<!ATTLIST chg n CDATA #IMPLIED>
<!ATTLIST chg src CDATA #IMPLIED>
<!ATTLIST chg date CDATA #IMPLIED>
<!ATTLIST chg user CDATA #IMPLIED>
<!ATTLIST chg href CDATA #IMPLIED>
<!ATTLIST chg note CDATA #IMPLIED>
<!ATTLIST hwtype n (alt | sub | fem | neu | n) #REQUIRED>
<!ATTLIST hwtype ref CDATA #REQUIRED>
<!-- 04-15-2024
<!ATTLIST lang n (greek | arabic | meter |slavic|russian|oldhebrew|Old-Church-Slavonic|Arabic|Hindustani|Persian|Turkish|hebrew|Avestan|Slavonic|Lettish|German|mongolian|UNK) #IMPLIED>
<!ATTLIST lang script (Arabic) #IMPLIED >
-->
<!ATTLIST lang n CDATA #IMPLIED>
<!ATTLIST lang script CDATA #IMPLIED>
<!ATTLIST arab lang CDATA #IMPLIED> <!-- 04-16-2024 -->
<!ATTLIST pic name CDATA #REQUIRED>
<!ATTLIST ab n CDATA #IMPLIED>
<!ATTLIST per n CDATA #IMPLIED>
<!ATTLIST lbinfo n CDATA #REQUIRED>
<!ATTLIST s1 slp1 CDATA #IMPLIED> <!-- 08-21-2024 probably can delete -->
<!ATTLIST s1 n CDATA #IMPLIED>  <!-- 08-21-2024 -->
<!ATTLIST vlex type (root) #REQUIRED>
<!ATTLIST C n (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12) #REQUIRED>
<!ATTLIST note  n (1) #REQUIRED>
<!-- <!ATTLIST is n (1) #IMPLIED> PWK-->
<!ATTLIST is n CDATA #IMPLIED>
<!ATTLIST ls n CDATA #IMPLIED>
<!ATTLIST hom n (pwk) #IMPLIED>
<!ATTLIST info seq CDATA #IMPLIED>
<!ATTLIST info n CDATA #IMPLIED>
<!ATTLIST listinfo n CDATA #IMPLIED>
<!ATTLIST info part CDATA #IMPLIED>

<!ATTLIST info and CDATA #IMPLIED >
<!ATTLIST info lex CDATA #IMPLIED >
<!ATTLIST info lexcat CDATA #IMPLIED >
<!ATTLIST info or CDATA #IMPLIED >
<!ATTLIST info orsl CDATA #IMPLIED >
<!ATTLIST info orwr CDATA #IMPLIED >
<!ATTLIST info phwchild CDATA #IMPLIED >
<!ATTLIST info phwparent CDATA #IMPLIED >
<!ATTLIST info verb (root|genuineroot|pre|gati|nom) #IMPLIED >
<!ATTLIST info westergaard CDATA #IMPLIED >
<!ATTLIST info whitneyroots CDATA #IMPLIED >
<!ATTLIST info pc CDATA #IMPLIED >
<!ATTLIST info vn CDATA #IMPLIED > <!-- GRA -->
<!ATTLIST info hui CDATA #IMPLIED > <!-- MW list display -->

<!ATTLIST mark n (P | H | Picture) #REQUIRED>
<!ATTLIST edit type (hw) #REQUIRED>
<!ATTLIST lex type (hw | hwalt | hwifc | hwinfo | nhw | part | phw ) #IMPLIED >
<!ATTLIST info cp CDATA #IMPLIED >
<!ATTLIST info parse CDATA #IMPLIED >
<!ATTLIST pb n CDATA #IMPLIED >
<!ATTLIST ab slp1 CDATA #IMPLIED >
<!ATTLIST bot n CDATA #IMPLIED >

=== arvicco/nabu/test/fixtures/mw/mw.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mw SYSTEM "mw.dtd">
<!-- Copyright Universitat Koln 2013 -->
<mw>
<H1><h><key1>aMSa</key1><key2>a/MSa</key2></h><body><s>a/MSa</s>   <lex>m.</lex> (probably <ab>fr.</ab> √ <hom>1.</hom> <s>aS</s>, <ab>perf.</ab> <s>An-a/MSa</s>, and not from the above √ <s>aMS</s> fictitiously formed to serve as root), a share, portion, part, party<info lex="m"/></body><tail><L>10</L><pc>1,1</pc></tail></H1>
<H1A><h><key1>aMSa</key1><key2>a/MSa</key2></h><body>  partition, inheritance<info lex="inh"/></body><tail><L>11</L><pc>1,1</pc></tail></H1A>
<H1A><h><key1>aMSa</key1><key2>a/MSa</key2></h><body>  a share of booty<info lex="inh"/></body><tail><L>12</L><pc>1,1</pc></tail></H1A>
<H1A><h><key1>aMSa</key1><key2>a/MSa</key2></h><body>  earnest money<info lex="inh"/></body><tail><L>13</L><pc>1,1</pc></tail></H1A>
<H1A><h><key1>aMSa</key1><key2>a/MSa</key2></h><body>  stake (in betting), <ls>RV. v, 86, 5</ls>; <ls>TāṇḍyaBr.</ls><info lex="inh"/></body><tail><L>14</L><pc>1,1</pc></tail></H1A>
<H1A><h><key1>aMSa</key1><key2>a/MSa</key2></h><body>  a lot (<ab>cf.</ab> <hom>2.</hom> <s>prA<srs/>s</s>)<info lex="inh"/></body><tail><L>15</L><pc>1,1</pc></tail></H1A>
<H1A><h><key1>aMSa</key1><key2>a/MSa</key2></h><body>  the denominator of a fraction<info lex="inh"/></body><tail><L>16</L><pc>1,1</pc></tail></H1A>
<H1A><h><key1>aMSa</key1><key2>a/MSa</key2></h><body>  a degree of latitude or longitude<info lex="inh"/></body><tail><L>17</L><pc>1,1</pc></tail></H1A>
<H1A><h><key1>aMSa</key1><key2>a/MSa</key2></h><body>  a day, <ls>L.</ls><info lex="inh"/></body><tail><L>18</L><pc>1,1</pc></tail></H1A>
<H1A><h><key1>aMSa</key1><key2>a/MSa</key2></h><body>  <ab>N.</ab> of an <s1>Āditya</s1>.<info lex="inh"/></body><tail><L>19</L><pc>1,1</pc></tail></H1A>
<H3><h><key1>aMSakaraRa</key1><key2>aMSa—karaRa</key2></h><body><s>aMSa—karaRa</s>   <lex>n.</lex> act of dividing.<info lex="n"/></body><tail><L>20</L><pc>1,1</pc></tail></H3>
<H3><h><key1>aMSaBU</key1><key2>aMSa—BU/</key2></h><body><s>aMSa—BU/</s>   <lex>m.</lex> partner, associate, <ls>TS.</ls><info lex="m"/></body><tail><L>26</L><pc>1,1</pc></tail></H3>
<H3><h><key1>aMSaBUta</key1><key2>aMSa—BUta</key2></h><body><s>aMSa—BUta</s>   <lex>mfn.</lex> forming part of.<info lex="m:f:n"/></body><tail><L>27</L><pc>1,1</pc></tail></H3>
<H3><h><key1>aMSarUpiRI</key1><key2>aMSa-rUpiRI</key2></h><body><s>aMSa-rUpiRI</s>   <lex>f.</lex> (with <s>Sakti</s>) a female personification of the divine energy, <ls>RTL. 187</ls>.<info n="sup"/><info lex="f"/></body><tail><L>27.1</L><pc>1308,1</pc></tail></H3>
<H2><h><key1>aMSala</key1><key2>aMSala</key2></h><body><s>aMSala</s>   See <s>aMsala/</s> next <ab>col.</ab></body><tail><L>44</L><pc>1,1</pc></tail></H2>
<H1><h><key1>aMs</key1><key2>aMs</key2></h><body><s>aMs</s>   (<ab>cf.</ab> √ <s>aMS</s>), <ls>L.</ls> See <s>vyaMs</s><info verb="genuineroot" cp=""/></body><tail><L>87</L><pc>1,2</pc></tail></H1>
<H2><h><key1>aMsa</key1><key2>a/Msa</key2></h><body><s>a/Msa</s>   <lex>m.</lex> the shoulder, shoulder-blade<info lex="m"/></body><tail><L>88</L><pc>1,2</pc></tail></H2>
<H2A><h><key1>aMsa</key1><key2>a/Msa</key2></h><body>  corner of a quadrangle<info lex="inh"/></body><tail><L>89</L><pc>1,2</pc></tail></H2A>
<H2A><h><key1>aMsa</key1><key2>a/Msa</key2></h><body>  <ab>N.</ab> of a king<info lex="inh"/></body><tail><L>90</L><pc>1,2</pc></tail></H2A>
<H2B><h><key1>aMsa</key1><key2>a/Msa</key2></h><body><s>a/Msa</s>   <lex>m. <ab>du.</ab></lex> the two shoulders or angles of an altar<info lex="m"/></body><tail><L>91</L><pc>1,2</pc></tail></H2B>
<H2B><h><key1>aMsa</key1><key2>a/Msa</key2></h><body>  a share (for <s>aMSa</s>); <info lex="inh"/></body><tail><L>92</L><pc>1,2</pc></tail></H2B>
<H2E><h><key1>aMsa</key1><key2>aMsa</key2></h><body><s>aMsa</s>   [<ab>cf.</ab> <lang>Goth.</lang> <etym>amsa</etym>; <lang>Gk.</lang> <gk>ὦμος</gk>, <gk>ἄσιλλα</gk>; <lang>Lat.</lang> <etym>humerus</etym>, <etym>ansa</etym>.]</body><tail><L>92.1</L><pc>1,2</pc></tail></H2E>
<H1><h><key1>akUpAra</key1><key2>a/-kUpAra</key2></h><body><s>a/-kUpAra</s>   <lex>mfn.</lex> unbounded, <ls>RV. v, 39, 2</ls> and <ls n="RV.">x, 109, 1</ls><info lex="m:f:n"/></body><tail><L>313</L><pc>2,2</pc></tail></H1>
<H1><h><key1>BAz</key1><key2>BAz</key2><hom>1</hom></h><body><hom>1.</hom> <s>BAz</s>   <ab>cl.</ab> 1. <ab>Ā.</ab> (<ls>Dhātup. xvi, 11</ls>) <s>BA/zate</s> (<lang>ep.</lang> also <ab>P.</ab> <s>˚ti</s>; <ab>pf.</ab> <s>baBAze</s>, <ls>Br.</ls> &amp;c.; <ab>fut.</ab> <s>BAzizyate</s> or <s>BAzitA</s> <ab>Gr.</ab>: <ab>aor.</ab> <s>aBAzizi</s>, <s>˚zWAH</s>, <s>˚zata</s>, <ls>Bhaṭṭ.</ls>; <ab>inf.</ab> <s>BAzitum</s>, <ls>Up.</ls>; <s>BAzwum</s>, <ls>MBh.</ls>; <ab>ind.p.</ab> <s>BAzitvA</s>, <s>-BAzya</s>, <ls>ib.</ls>), <div n="to"/>to speak, talk, say, tell (with <ab>acc.</ab> of thing or person, sometimes also with <ab>acc.</ab> of thing and person), <ls>Br.</ls> &amp;c. &amp;c.; <div n="to"/>to speak of or about or on (<ab>acc.</ab>), <ls>Kām.</ls>; <div n="to"/>to announce, declare, <ls>Gobh.</ls>; <div n="to"/>to call, name, describe as (with two <ab>acc.</ab>), <ls>Mn.</ls>; <ls>Śrutab.</ls>; <div n="to"/>to use or employ in speaking, <ls>Nir.</ls>; <ls>Suśr.</ls>; <div n="to"/> <ab>Pass.</ab> <s>BAzyate</s> (<ab>aor.</ab> <s>aBAzi</s>), to be spoken, be addressed or spoken to, <ls>MBh.</ls>; <ls>Kāv.</ls> &amp;c.: <div n="vp"/><ab>Caus.</ab> <s>BAzayati</s>, <s>˚te</s> (<ab>aor.</ab> <s>abaBAzat</s> or <s>abIBazat</s>, <ls>Pāṇ. vii, 4, 3</ls>), to cause to speak or talk, <ls>MārkP.</ls> <pb n="755,3"/>; <div n="to"/>to cause to speak <ab>i.e.</ab> to think, agitate, disquiet, <ls>R.</ls>; <div n="to"/>to say, speak, <ls>MBh.</ls> : <div n="vp"/><ab>Desid.</ab>, <s>biBAzizate</s> <ab>Gr.</ab>: <div n="vp"/><ab>Intens.</ab> <s>bABAzyate</s>, <s>bABAzwi</s>, <ls>ib.</ls> (sometimes confounded with <s>Baz</s>; <ab>cf.</ab> √ <s>BaR</s> and <s>BAs</s>). <info westergaard="BAza,16.11,01.0396"/><info whitneyroots="BAz,110"/><info verb="genuineroot" cp="1Ā,1P"/><info hui="1"/></body><tail><L>150479</L><pc>755,2</pc></tail></H1>
<H2><h><key1>BAzaRa</key1><key2>BAzaRa</key2></h><body><s>BAzaRa</s>   <lex>n.</lex> (<ab>ifc.</ab> <lex type="hwifc">f(<s>A</s>). </lex>) the act of speaking, talking, speech, talk, <ls>Nir.</ls>; <ls>Mn.</ls>; <ls>MBh.</ls> &amp;c.<info lex="f#A:n"/></body><tail><L>150481</L><pc>755,3</pc></tail></H2>
<H2A><h><key1>BAzaRa</key1><key2>BAzaRa</key2></h><body>  kind words, kindness (= <s>sAma-dAnA<srs/>di</s>), <ls>Sāh.</ls><info lex="inh"/></body><tail><L>150482</L><pc>755,3</pc></tail></H2A>
</mw>
